apiVersion: v1
kind: PersistentVolume
metadata:
  name: devops-nexus-pv
  namespace: devops
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: kcsnanasapp46.kcs
    # FIXME: use the right nfs path
    path: "/NDEVSECOPS/devops/nexus"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devops-nexus-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
