apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nexus
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus
  template:
    metadata:
      name: nexus
      labels:
        name: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
        # imagePullPolicy: IfNotPresent
        ports:
        - name: nexus
          containerPort: 8081
          containerPort: 5000
          
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data

      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: devops-nexus-pvc
